package main

import (
	"math/rand"
	"time"
)

var scientificFacts = []string{
	"Potassium has the atomic number 19.",
	"It is represented by the symbol 'K' from the Latin 'kalium'.",
	"Potassium is an alkali metal.",
	"It has one electron in its outer shell.",
	"Potassium is highly reactive, especially with water.",
	"It has a melting point of 63.5°C (146.3°F).",
	"Potassium boils at 759°C (1398°F).",
	"It has a density of 0.89 g/cm³.",
	"Potassium ions (K⁺) are essential in cell function.",
	"K⁺ is crucial for nerve transmission and muscle contraction.",
	"Potassium is more reactive than sodium.",
	"It has an electron configuration of [Ar] 4s¹.",
	"Potassium was first isolated in 1807 by Humphry Davy.",
	"Natural potassium contains the isotope K-40, which is radioactive.",
	"K-40 is used in radiometric dating.",
	"Potassium is the 7th most abundant element in Earth's crust.",
	"It has a silvery appearance but tarnishes quickly in air.",
	"Potassium reacts violently with water to produce hydrogen gas.",
	"The reaction of potassium with water produces heat and a purple flame.",
	"K⁺ ions help regulate fluid balance in the body.",
	"Low potassium levels cause hypokalemia.",
	"High potassium levels cause hyperkalemia.",
	"Potassium is absorbed in the small intestine.",
	"It is excreted mainly through the kidneys.",
	"Potassium chloride (KCl) is a common supplement.",
	"Plants absorb potassium as a macronutrient.",
	"Potassium is essential for photosynthesis in plants.",
	"K⁺ helps maintain cell turgor pressure in plants.",
	"KCl is used in fertilizers as 'muriate of potash'.",
	"Potassium nitrate (KNO₃) is used in gunpowder.",
	"K-40 has a half-life of about 1.25 billion years.",
	"Potassium-39 and potassium-41 are stable isotopes.",
	"K⁺ channels regulate heart rhythm.",
	"Potassium salts are soluble in water.",
	"K⁺ plays a role in ATP synthesis.",
	"Potassium helps activate enzymes.",
	"Potassium carbonate (K₂CO₃) is known as potash.",
	"K⁺ is vital in maintaining intracellular pH.",
	"Potassium metal is stored under oil.",
	"Potassium's electronegativity is 0.82 (Pauling scale).",
	"K⁺ is involved in glucose metabolism.",
	"KCl is used medically for electrolyte replenishment.",
	"K⁺ helps maintain normal blood pressure.",
	"Potassium permanganate (KMnO₄) is a strong oxidizer.",
	"Potassium reacts with halogens to form salts.",
	"K⁺ channels are targets for many drugs.",
	"Potassium fluoride (KF) is used in etching glass.",
	"Potassium is softer than most metals—can be cut with a knife.",
	"K⁺ affects resting membrane potential in neurons.",
	"Potassium's standard electrode potential is -2.93 V.",
}

var funFacts = []string{
	"Bananas are famously rich in potassium, but not the best source.",
	"A banana contains about 422 mg of potassium.",
	"Too much potassium at once can stop your heart.",
	"Potassium burns with a lilac flame.",
	"Potassium is so reactive, it explodes in water.",
	"Pure potassium looks like a shiny metal—until it oxidizes instantly.",
	"NASA uses potassium in heat transfer systems for spacecraft.",
	"Potassium is used in fireworks to produce purple colors.",
	"The name 'potassium' comes from potash, made from wood ash.",
	"Potassium soap was one of the first industrial chemicals.",
	"Your body contains about 120 grams of potassium.",
	"Potassium deficiency can make your muscles feel weak.",
	"Potassium chloride is used in lethal injections.",
	"The 'K' in Gatorade's ingredients is usually potassium citrate.",
	"Avocados have more potassium than bananas.",
	"Potassium was the first metal isolated using electrolysis.",
	"You can’t find pure potassium in nature—it’s too reactive.",
	"A potassium overdose is called potassium poisoning or hyperkalemia.",
	"Potassium can ignite spontaneously in moist air.",
	"Potassium makes up about 2.4% of Earth's crust by weight.",
	"Potassium helps you poop—seriously, it aids peristalsis.",
	"Low potassium can cause irregular heartbeat.",
	"Tomatoes, potatoes, and oranges are good potassium sources.",
	"Potassium nitrate was once called 'saltpeter'.",
	"K⁺ is so important that your body hoards it like treasure.",
	"Potassium tablets are often wax-coated to prevent stomach irritation.",
	"Potassium permanganate used to be a household antiseptic.",
	"Blood potassium levels are tightly regulated by hormones.",
	"You pee out most of your excess potassium.",
	"Potassium soap lathers better in hard water than sodium soap.",
	"Some bacteria can use potassium gradients to swim.",
	"Potassium helps keep your brain signals firing correctly.",
	"Potassium is essential for frogs to jump—really.",
	"Dehydration often leads to low potassium.",
	"Potassium is listed as E508 in food additives.",
	"K⁺ is important in sports performance and recovery.",
	"Your kidneys adjust potassium output within hours.",
	"Potassium citrate can prevent kidney stones.",
	"Potassium acetate is used as a de-icer for airport runways.",
	"Potassium was involved in early theories of electricity.",
	"Without potassium, your heart would literally stop.",
	"Some water softeners use potassium chloride instead of sodium.",
	"Potassium can reduce cramps during workouts.",
	"Potassium hydroxide is used to make biodiesel.",
	"Potassium supplements can interact with medications dangerously.",
	"K⁺ gradients are vital in digital neural implants.",
	"Potassium helps with carbohydrate metabolism.",
	"KCl is used to stop the heart in surgery (under strict control).",
	"Potassium soap is better for your skin than sodium soap.",
	"Too little potassium makes you feel like a bag of wet socks.",
	"Your body throws a tantrum if potassium levels drop too fast.",
}

// GetRandomPotassiumFact returns a random potassium fact from the combined list.
func GetRandomPotassiumFact() string {
	rand.Seed(time.Now().UnixNano())
	allFacts := append(scientificFacts, funFacts...)
	return allFacts[rand.Intn(len(allFacts))]
}

